#!/bin/bash
cat << Main_Menu
Task :: Create a script to list the IP addresses your computer is connected to and the interface status.
1> Run Expression
2> Open in Nano
3> Exit
Main_Menu
#####################################################
function expression(){
echo "The following interfaces are in the 'up' state"

ip addr | awk '
/^[0-9]+:/ {
  sub(/:/,"",$2); iface=$2 }
/^[[:space:]]*inet / {
  split($2, a, "/")
 print iface" : "a[1]
}'
}

read n
case $n in
    1) expression;;
    2) nano /home/Ansel/test2.0.sh;;
    3) break;;
    *) invalid option;;
esac
